version: '3.9'

services:
  pgsql:
    restart: always
    image: postgres:13
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: maki
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
